databases:
  - name: siddhu-django-db
    databaseName: siddhu_django
    user: siddhu_user

services:
  - type: web
    name: siddhu-django-app
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn function_scheduler.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: siddhu-django-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
